<?php

declare(strict_types=1);

namespace Webrium\View;

/**
 * Webrium\\View - Lightweight view engine + hybrid static cache (no eval)
 *
 * This version delegates all template parsing/compilation to Parser::compile()
 * (no DOMDocument usage). It keeps the same public API as previous versions:
 *
 *  - Engine::render($view, $data = [])
 *  - Engine::renderLayout($layoutView, $view, $data = [])
 *  - Engine::renderLayoutWithSections($layoutView, $sections, $data = [])
 *  - Engine::component($view, $data = [])
 *  - Engine::hybrid($view, $key, $dataOrFactory = null, ?int $ttl = null)
 *  - Engine::hybridLayout($layoutView, $view, $key, $dataOrFactory = null, ?int $ttl = null)
 *  - Engine::hybridSection($view, $section, $key, $dataOrFactory = null, ?int $ttl = null)
 *  - Engine::hybridComponent($view, $key, $dataOrFactory = null, ?int $ttl = null)
 *  - Engine::remember($namespace, $key, $renderer, ?int $ttl = null)
 *  - Engine::staticFile($path)
 *  - Engine::clearStatics(), Engine::clearCompiled()
 *
 * It also supports:
 *  - Hybrid cache comment with a precise ISO-8601 expiration timestamp
 *  - Raw PHP directive policy via allowRawPhpDirective()/isRawPhpDirectiveAllowed()
 */

class ViewException extends \RuntimeException
{
    /**
     * The original (human-readable) view path before compilation.
     * Set when the exception originates inside a compiled template file.
     * External error handlers (e.g. Core/Debug) can call getOriginalView()
     * without importing this class — plain duck-typing is enough.
     */
    private string $originalView = '';

    /** Original one-based line number in the view source, when known. */
    private int $originalLine = 0;

    /** Compiled template path that produced the error, when applicable. */
    private string $compiledView = '';



    public function setOriginalView(string $view): static
    {
        $this->originalView = $view;
        return $this;
    }

    /** Returns the original view path, or empty string if not set. */
    public function getOriginalView(): string
    {
        return $this->originalView;
    }

    public function setOriginalLine(int $line): static
    {
        $this->originalLine = max(0, $line);
        return $this;
    }

    public function getOriginalLine(): int
    {
        return $this->originalLine;
    }

    public function setCompiledView(string $view): static
    {
        $this->compiledView = $view;
        return $this;
    }

    public function getCompiledView(): string
    {
        return $this->compiledView;
    }
}

class ViewTemplateException extends ViewException {}

class Engine
{
    /**
     * Base directory for view files.
     * Relative paths are resolved from the current working directory.
     */
    protected static string $viewDir = 'views';

    /**
     * Base directory for static / cached rendered pages (hybrid).
     */
    protected static string $staticDir = 'static';

    /**
     * Base directory for compiled PHP templates.
     */
    protected static string $compiledDir = 'storage/view_compiled';

    /**
     * Default hybrid cache TTL in seconds (one week).
     */
    protected static ?int $defaultHybridCacheTtl = 604800;

    /**
     * Global switch for all hybrid cache writes and reads.
     */
    protected static bool $hybridCacheEnabled = true;

    /**
     * Whether @php(...) directive is allowed.
     * If set to false, any use of @php will throw an exception in Parser.
     */
    protected static bool $allowRawPhpDirective = true;

    private const COMPILED_HEADER_LINES = 3;
    private const SOURCE_MAP_VERSION = 1;

    /**
     * Regex to detect the autogenerated cache comment in static files.
     */
    protected const CACHE_COMMENT_PATTERN =
        '/<!--\s*Automatically generated by webrium-view:\s*\[ex:([^\]]+)\]\s*-->/i';

    // Cache duration constants
    public const CACHE_NONE     = 0;
    public const CACHE_A_MINUTE = 60;
    public const CACHE_AN_HOUR  = 3600;
    public const CACHE_A_DAY    = 86400;
    public const CACHE_A_WEEK   = 604800;

    // Alias kept intentionally for compatibility with your sample code
    public const CACH_A_WEEK = 604800;

    /* ============================================================
     * Configuration
     * ============================================================
     */

    /**
     * Configure the base directory for views.
     */
    public static function setViewDir(string $dir): void
    {
        $dir = rtrim($dir, "/\\");
        if ($dir === '') {
            throw new ViewException('View directory cannot be empty.');
        }
        self::$viewDir = $dir;
    }

    /**
     * Configure the base directory for static / cached files.
     */
    public static function setStaticDir(string $dir): void
    {
        $dir = rtrim($dir, "/\\");
        if ($dir === '') {
            throw new ViewException('Static directory cannot be empty.');
        }
        self::$staticDir = $dir;
    }

    /**
     * Configure the base directory for compiled templates.
     */
    public static function setCompiledDir(string $dir): void
    {
        $dir = rtrim($dir, "/\\");
        if ($dir === '') {
            throw new ViewException('Compiled directory cannot be empty.');
        }
        self::$compiledDir = $dir;
    }

    /**
     * Optionally override the default hybrid cache TTL (in seconds).
     * Pass null to disable default TTL and force explicit TTL in hybrid().
     */
    public static function setDefaultHybridCacheTtl(?int $seconds): void
    {
        if ($seconds !== null && $seconds < 0) {
            throw new ViewException('Default cache TTL cannot be negative.');
        }
        self::$defaultHybridCacheTtl = $seconds;
    }

    /**
     * Enable or disable all hybrid cache reads and writes at runtime.
     */
    public static function enableHybridCache(bool $enabled): void
    {
        self::$hybridCacheEnabled = $enabled;
    }

    public static function isHybridCacheEnabled(): bool
    {
        return self::$hybridCacheEnabled;
    }

    /**
     * Enable / disable @php(...) directive.
     */
    public static function allowRawPhpDirective(bool $allow): void
    {
        self::$allowRawPhpDirective = $allow;
    }

    /**
     * Return current policy for @php(...) directive.
     * Used by Parser::compile().
     */
    public static function isRawPhpDirectiveAllowed(): bool
    {
        return self::$allowRawPhpDirective;
    }

    /* ============================================================
     * Public API
     * ============================================================
     */

    /**
     * Magic handler so you can call Engine::static('file') conveniently.
     *
     * NOTE:
     *   Recommended direct method is Engine::staticFile('path/to/file.ext').
     */
    public static function __callStatic(string $name, array $arguments)
    {
        if ($name === 'static') {
            if (count($arguments) !== 1) {
                throw new ViewException('Engine::static() expects exactly 1 argument (relative static file path).');
            }
            return self::staticFile((string) $arguments[0]);
        }

        throw new ViewException("Undefined static method Engine::{$name}().");
    }

    /**
     * Read a static file from the static directory and return its raw contents.
     * No parsing or processing is performed.
     */
    public static function staticFile(string $relativePath): string
    {
        $relativePath = ltrim($relativePath, "/\\");
        $baseDir      = self::getStaticDir();
        $fullPath     = $baseDir . DIRECTORY_SEPARATOR . $relativePath;

        $realBase = realpath($baseDir);
        $realFile = realpath($fullPath);

        // Prevent directory traversal
        if ($realBase !== false && $realFile !== false && strpos($realFile, $realBase) !== 0) {
            throw new ViewException('Invalid static file path (path traversal not allowed).');
        }

        if (!is_file($fullPath)) {
            throw new ViewException("Static file not found: {$fullPath}");
        }

        $content = @file_get_contents($fullPath);
        if ($content === false) {
            throw new ViewException("Unable to read static file: {$fullPath}");
        }

        return $content;
    }

    /**
     * Render a view file using the Webrium View engine.
     *
     * @param string $view  Relative view path (e.g., 'productView.php')
     * @param array  $data  Variables to make available in the view
     *
     * @return string Rendered HTML
     */
    public static function render(string $view, array $data = []): string
    {
        $viewPath     = self::resolveViewPath($view);
        $compiledPath = self::compileViewIfNeeded($viewPath);

        return self::evaluateCompiledFile($compiledPath, $data, $viewPath);
    }

    /**
     * Render a view inside a layout using the section / yield API.
     *
     * @param string $layoutView Layout view (e.g. 'layouts/main.php')
     * @param string $view       Child view (e.g. 'pages/home.php')
     * @param array  $data       Shared data for both views
     */
    public static function renderLayout(
        string $layoutView,
        string $view,
        array $data = []
    ): string {
        return View::renderWithLayout($view, $layoutView, $data);
    }

    /**
     * Render a layout from already-rendered sections.
     *
     * This is useful when a controller caches an expensive content section but
     * keeps the surrounding layout, header, and user-specific UI dynamic.
     *
     * @param array<string,string> $sections
     */
    public static function renderLayoutWithSections(
        string $layoutView,
        array $sections,
        array $data = []
    ): string {
        return View::renderLayoutWithSections($layoutView, $sections, $data);
    }

    /**
     * Render a view as a component / partial.
     *
     * Can be called directly from PHP or via @component(...) in templates.
     */
    public static function component(string $view, array $data = []): string
    {
        return View::component($view, $data);
    }

    /**
     * Hybrid rendering with optional lazy data factory.
     *
     * @param string               $view          View file to render
     * @param string|array         $key           Cache key (string or array)
     * @param array|callable|null  $dataOrFactory Data array, lazy factory, or null (read-only mode)
     * @param int|null             $cacheTtl      TTL in seconds (null => use default)
     *
     * @return string|false Rendered content or false in read-only mode when cache is missing/expired
     */
    public static function hybrid(
        string $view,
        string|array $key,
        array|callable|null $dataOrFactory = null,
        ?int $cacheTtl = null
    ): string|false {
        return self::hybridRender(
            'view:' . $view,
            $key,
            $dataOrFactory,
            $cacheTtl,
            fn (array $data): string => self::render($view, $data)
        );
    }

    /**
     * Cache a complete child + layout render. Only use this when the entire
     * response is identical for every request sharing the supplied key.
     */
    public static function hybridLayout(
        string $layoutView,
        string $view,
        string|array $key,
        array|callable|null $dataOrFactory = null,
        ?int $cacheTtl = null
    ): string|false {
        return self::hybridRender(
            'layout:' . $layoutView . '>' . $view,
            $key,
            $dataOrFactory,
            $cacheTtl,
            fn (array $data): string => self::renderLayout($layoutView, $view, $data)
        );
    }

    /**
     * Cache one named section from a child view and return its rendered HTML.
     * The controller can inject the result into a dynamic layout with
     * renderLayoutWithSections().
     */
    public static function hybridSection(
        string $view,
        string $section,
        string|array $key,
        array|callable|null $dataOrFactory = null,
        ?int $cacheTtl = null
    ): string|false {
        $section = trim($section);
        if ($section === '') {
            throw new ViewException('Hybrid section name cannot be empty.');
        }

        return self::hybridRender(
            'section:' . $view . '#' . $section,
            $key,
            $dataOrFactory,
            $cacheTtl,
            fn (array $data): string => View::renderSection($view, $section, $data)
        );
    }

    /**
     * Cache a reusable component/partial with controller-provided lazy data.
     */
    public static function hybridComponent(
        string $view,
        string|array $key,
        array|callable|null $dataOrFactory = null,
        ?int $cacheTtl = null
    ): string|false {
        return self::hybridRender(
            'component:' . $view,
            $key,
            $dataOrFactory,
            $cacheTtl,
            fn (array $data): string => self::component($view, $data)
        );
    }

    /**
     * Cache arbitrary controller-rendered HTML behind a namespace and key.
     * The renderer runs only on a cache miss. It must return a string.
     */
    public static function remember(
        string $namespace,
        string|array $key,
        callable $renderer,
        ?int $cacheTtl = null
    ): string {
        $namespace = trim($namespace);
        if ($namespace === '') {
            throw new ViewException('Hybrid cache namespace cannot be empty.');
        }

        $result = self::cacheRendered(
            'remember:' . $namespace,
            $key,
            function () use ($renderer): string {
                $content = $renderer();
                if (!is_string($content)) {
                    throw new ViewException('Hybrid cache renderer must return a string.');
                }
                return $content;
            },
            $cacheTtl,
            false
        );

        return $result;
    }

    /**
     * Shared implementation for view, layout, section, and component caches.
     *
     * Direct arrays intentionally force a refresh for backward compatibility.
     * Lazy factories run only on a miss or after expiry. Null performs a
     * read-only lookup.
     */
    protected static function hybridRender(
        string $identity,
        string|array $key,
        array|callable|null $dataOrFactory,
        ?int $cacheTtl,
        callable $renderer
    ): string|false {
        if ($dataOrFactory === null) {
            if (!self::$hybridCacheEnabled) {
                return false;
            }

            return self::readFreshCache(self::getHybridStaticPath($identity, $key));
        }

        if (is_array($dataOrFactory)) {
            return self::cacheRendered(
                $identity,
                $key,
                fn (): string => $renderer($dataOrFactory),
                $cacheTtl,
                true
            );
        }

        if (is_callable($dataOrFactory)) {
            return self::cacheRendered(
                $identity,
                $key,
                function () use ($dataOrFactory, $renderer): string {
                    $data = $dataOrFactory();
                    if (!is_array($data)) {
                        throw new ViewException('Hybrid data factory must return an array.');
                    }

                    return $renderer($data);
                },
                $cacheTtl,
                false
            );
        }

        throw new ViewException(
            'Hybrid data must be an array, a callable, or null.'
        );
    }

    /**
     * Cache the output of a lazy renderer with stampede protection.
     */
    protected static function cacheRendered(
        string $identity,
        string|array $key,
        callable $renderer,
        ?int $cacheTtl,
        bool $forceRefresh
    ): string {
        if (!self::$hybridCacheEnabled) {
            return self::renderCacheContent($renderer);
        }

        $staticPath = self::getHybridStaticPath($identity, $key);
        $ttlSeconds = self::resolveHybridCacheTtl($cacheTtl);
        if ($ttlSeconds === self::CACHE_NONE) {
            if (is_file($staticPath)) {
                @unlink($staticPath);
            }

            return self::renderCacheContent($renderer);
        }

        if (!$forceRefresh) {
            $cached = self::readFreshCache($staticPath);
            if ($cached !== false) {
                return $cached;
            }
        }

        $dir = dirname($staticPath);
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new ViewException('Unable to create hybrid cache directory: ' . $dir);
        }

        $lockPath = $staticPath . '.lock';
        $lock = @fopen($lockPath, 'c');
        if ($lock === false) {
            throw new ViewException('Unable to open hybrid cache lock: ' . $lockPath);
        }

        try {
            if (!flock($lock, LOCK_EX)) {
                throw new ViewException('Unable to acquire hybrid cache lock: ' . $lockPath);
            }

            // Another request may have populated the cache while this request
            // waited for the lock, so check one more time before rendering.
            if (!$forceRefresh) {
                $cached = self::readFreshCache($staticPath);
                if ($cached !== false) {
                    return $cached;
                }
            }

            $output = self::renderCacheContent($renderer);
            return self::writeHybridCache($staticPath, $output, $ttlSeconds);
        } finally {
            flock($lock, LOCK_UN);
            fclose($lock);
        }
    }

    protected static function renderCacheContent(callable $renderer): string
    {
        $output = $renderer();
        if (!is_string($output)) {
            throw new ViewException('Hybrid cache renderer must return a string.');
        }

        return $output;
    }

    protected static function resolveHybridCacheTtl(?int $cacheTtl): int
    {
        if ($cacheTtl === null) {
            if (self::$defaultHybridCacheTtl === null) {
                throw new ViewException(
                    'Hybrid cache TTL must be provided when no default TTL is configured.'
                );
            }

            $cacheTtl = self::$defaultHybridCacheTtl;
        }

        if ($cacheTtl < 0) {
            throw new ViewException('Hybrid cache TTL cannot be negative.');
        }

        return $cacheTtl;
    }

    protected static function readFreshCache(string $staticPath): string|false
    {
        if (!is_file($staticPath)) {
            return false;
        }

        $content = @file_get_contents($staticPath);
        if ($content === false) {
            return false;
        }

        $expiry = self::parseCacheExpiryFromStatic($content);
        if ($expiry === null || new \DateTimeImmutable('now') > $expiry) {
            return false;
        }

        return $content;
    }

    /**
     * Remove all static files in the configured static directory.
     * This does NOT remove the directory itself.
     */
    public static function clearStatics(): void
    {
        $dir = self::getStaticDir();
        if (!is_dir($dir)) {
            return;
        }

        $iterator = new \DirectoryIterator($dir);
        foreach ($iterator as $fileInfo) {
            if ($fileInfo->isDot()) {
                continue;
            }
            if ($fileInfo->isFile()) {
                @unlink($fileInfo->getPathname());
            }
        }
    }

    /**
     * Remove all compiled template files.
     * This does NOT remove the directory itself.
     */
    public static function clearCompiled(): void
    {
        $dir = self::getCompiledDir();
        if (!is_dir($dir)) {
            return;
        }

        $iterator = new \DirectoryIterator($dir);
        foreach ($iterator as $fileInfo) {
            if ($fileInfo->isDot()) {
                continue;
            }
            if ($fileInfo->isFile()) {
                @unlink($fileInfo->getPathname());
            }
        }
    }

    /* ============================================================
     * Internal helpers: directories & paths
     * ============================================================
     */

    /**
     * Resolve the absolute path to a view file.
     *
     * If the view string does not already end with the ".php" extension,
     * it is appended automatically. This allows both of the following:
     *   Engine::render('test.php');
     *   Engine::render('test');
     */
    protected static function resolveViewPath(string $view): string
    {
        $view = ltrim($view, "/\\");

        if (strtolower(substr($view, -4)) !== '.php') {
            $view .= '.php';
        }

        $dir  = self::getViewDir();
        $full = $dir . DIRECTORY_SEPARATOR . $view;

        if (!is_file($full)) {
            throw new ViewException("View file does not exist: {$full}");
        }

        return $full;
    }

    /**
     * Get and validate the view directory.
     */
    protected static function getViewDir(): string
    {
        $dir = self::$viewDir;
        if ($dir === '') {
            throw new ViewException('View directory is not configured.');
        }
        if (!is_dir($dir)) {
            throw new ViewException("View directory does not exist: {$dir}");
        }
        return $dir;
    }

    /**
     * Get (and lazily create) the static directory.
     */
    protected static function getStaticDir(): string
    {
        $dir = self::$staticDir;
        if ($dir === '') {
            throw new ViewException('Static directory is not configured.');
        }
        if (!is_dir($dir)) {
            if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
                throw new ViewException("Unable to create static directory: {$dir}");
            }
        }
        return $dir;
    }

    /**
     * Get (and lazily create) the compiled templates directory.
     */
    protected static function getCompiledDir(): string
    {
        $dir = self::$compiledDir;
        if ($dir === '') {
            throw new ViewException('Compiled directory is not configured.');
        }
        if (!is_dir($dir)) {
            if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
                throw new ViewException("Unable to create compiled directory: {$dir}");
            }
        }
        return $dir;
    }

    /**
     * Build the static filename used by hybrid() for a given view + key.
     */
    protected static function getHybridStaticPath(string $identity, string|array $key): string
    {
        $baseDir = self::getStaticDir();
        $identitySlug = (string) preg_replace('/[^A-Za-z0-9_-]+/', '-', $identity);
        $identitySlug = trim($identitySlug, '-_');
        $identitySlug = substr($identitySlug !== '' ? $identitySlug : 'hybrid', 0, 72);
        $identityHash = substr(sha1($identity), 0, 10);

        if (is_array($key)) {
            // Normalize array key so that the same logical key always produces the same hash
            $normalized = self::normalizeHybridKeyArray($key);

            $json = json_encode($normalized, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            if ($json === false) {
                throw new ViewException('Unable to JSON-encode hybrid cache key.');
            }

            $safeKey = 'key-' . substr(sha1($json), 0, 16);
        } else {
            $safeKey = (string) preg_replace('/[^A-Za-z0-9_\-]+/', '-', $key);
            $safeKey = trim($safeKey, '-_');
            if ($safeKey === '') {
                $safeKey = 'default';
            }
            $safeKey = substr($safeKey, 0, 72) . '-' . substr(sha1($key), 0, 10);
        }

        $fileName = $identitySlug . '-' . $identityHash . '-' . $safeKey . '.html';

        return $baseDir . DIRECTORY_SEPARATOR . $fileName;
    }

    /**
     * Normalize an array key into a stable structure for hashing.
     */
    protected static function normalizeHybridKeyArray(array $key): array
    {
        // Detect if the array is associative (or mixed)
        $isAssoc = !array_is_list($key);
        if ($isAssoc) {
            ksort($key);
        }

        $normalized = [];
        foreach ($key as $k => $v) {
            if (is_array($v)) {
                $normalized[$k] = self::normalizeHybridKeyArray($v);
            } else {
                $normalized[$k] = $v;
            }
        }

        return $normalized;
    }

    /**
     * Compile a view file into a cached PHP file if needed,
     * and return the compiled file path.
     */
    protected static function compileViewIfNeeded(string $viewPath): string
    {
        $compiledDir  = self::getCompiledDir();
        $hash         = sha1($viewPath);
        $compiledPath = $compiledDir . DIRECTORY_SEPARATOR . $hash . '.php';
        $sourceMapPath = self::getSourceMapPath($compiledPath);

        $needsCompile = true;

        if (is_file($compiledPath) && is_file($sourceMapPath)) {
            $viewMtime     = filemtime($viewPath) ?: 0;
            $compiledMtime = filemtime($compiledPath) ?: 0;

            // Recompile only if view is newer than compiled file
            if ($compiledMtime >= $viewMtime) {
                $needsCompile = false;
            }
        }

        if ($needsCompile) {
            $template = @file_get_contents($viewPath);
            if ($template === false) {
                throw new ViewException("Unable to read view file: {$viewPath}");
            }

            try {
                $compiledTemplate = self::compileTemplate($template);
            } catch (ViewTemplateException $exception) {
                $line = max(1, $exception->getOriginalLine());
                $mappedCause = new \ErrorException(
                    $exception->getMessage(),
                    (int) $exception->getCode(),
                    E_ERROR,
                    $viewPath,
                    $line,
                    $exception
                );

                throw (new ViewTemplateException(
                    $exception->getMessage(),
                    (int) $exception->getCode(),
                    $mappedCause
                ))
                    ->setOriginalView($viewPath)
                    ->setOriginalLine($line);
            }

            $header = "<?php\n"
                . "/* Compiled by Webrium\View from: {$viewPath} at " . date('c') . " */\n"
                . "?>\n";

            $compiledPhp = $header . $compiledTemplate->getCode();

            $sourceMap = [];
            for ($line = 1; $line <= self::COMPILED_HEADER_LINES; $line++) {
                $sourceMap[$line] = 1;
            }
            foreach ($compiledTemplate->getLineMap() as $generatedLine => $sourceLine) {
                $sourceMap[$generatedLine + self::COMPILED_HEADER_LINES] = $sourceLine;
            }

            $sourceMapJson = json_encode([
                'version' => self::SOURCE_MAP_VERSION,
                'source' => $viewPath,
                'lines' => $sourceMap,
            ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            if ($sourceMapJson === false) {
                throw new ViewException("Unable to encode compiled source map: {$sourceMapPath}");
            }

            if (@file_put_contents($compiledPath, $compiledPhp, LOCK_EX) === false) {
                throw new ViewException("Unable to write compiled template: {$compiledPath}");
            }
            if (@file_put_contents($sourceMapPath, $sourceMapJson, LOCK_EX) === false) {
                throw new ViewException("Unable to write compiled source map: {$sourceMapPath}");
            }
        }

        if (class_exists(\Webrium\Debug::class)) {
            \Webrium\Debug::registerCompiledFile($compiledPath, $viewPath);
        }

        return $compiledPath;
    }

    /**
     * Render view and store static version with expiration comment.
     */
    protected static function writeHybridCache(
        string $staticPath,
        string $output,
        int $ttlSeconds
    ): string {
        $expiry = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))
            ->add(new \DateInterval('PT' . $ttlSeconds . 'S'));
        $comment = '<!-- Automatically generated by webrium-view: [ex:'
            . $expiry->format(\DateTimeInterface::ATOM)
            . '] -->';

        $contentToWrite = $comment . "\n" . $output;

        $dir = dirname($staticPath);
        if (!is_dir($dir)) {
            if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
                throw new ViewException('Unable to create directory for static file: ' . $dir);
            }
        }

        $temporaryPath = $staticPath . '.' . bin2hex(random_bytes(6)) . '.tmp';
        if (@file_put_contents($temporaryPath, $contentToWrite, LOCK_EX) === false) {
            throw new ViewException('Failed to write temporary hybrid cache file: ' . $temporaryPath);
        }

        if (!@rename($temporaryPath, $staticPath)) {
            @unlink($temporaryPath);
            throw new ViewException('Failed to publish hybrid cache file: ' . $staticPath);
        }

        return $contentToWrite;
    }

    /**
     * Parse expiration date from a static file's autogenerated comment.
     */
    protected static function parseCacheExpiryFromStatic(string $content): ?\DateTimeImmutable
    {
        if (!preg_match(self::CACHE_COMMENT_PATTERN, $content, $matches)) {
            return null;
        }

        $expiryValue = trim((string) ($matches[1] ?? ''));
        if ($expiryValue === '') {
            return null;
        }

        // Read legacy date-only cache files until they naturally expire.
        if (preg_match('/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/', $expiryValue) === 1) {
            $legacy = \DateTimeImmutable::createFromFormat('!Y-m-d', $expiryValue);
            return $legacy === false ? null : $legacy->setTime(23, 59, 59);
        }

        try {
            return new \DateTimeImmutable($expiryValue);
        } catch (\Exception) {
            return null;
        }
    }

    /* ============================================================
     * Template compilation (delegated to Parser)
     * ============================================================
     */

    /**
     * Compile the raw template string into executable PHP+HTML string.
     *
     * All actual parsing is handled by Parser::compile().
     */
    protected static function compileTemplate(string $template): CompiledTemplate
    {
        return Parser::compileWithSourceMap($template);
    }

    /* ============================================================
     * Template evaluation (require compiled file)
     * ============================================================
     */

    /**
     * Evaluate a compiled template file with the given data (no eval).
     *
     * All keys in $data are extracted as variables.
     * Full array is also available as $zogData inside the template if needed.
     */
    protected static function evaluateCompiledFile(string $compiledPath, array $data, string $originalView = ''): string
    {
        $zogData = $data;
        $initialBufferLevel = ob_get_level();

        ob_start();

        set_error_handler(function (int $errno, string $errstr, string $errfile, int $errline) {
            throw new \ErrorException($errstr, $errno, $errno, $errfile, $errline);
        });

        try {
            (function () use ($compiledPath, $zogData) {
                if (!empty($zogData)) {
                    extract($zogData, EXTR_SKIP);
                }
                require $compiledPath;
            })();

            return (string) ob_get_clean();
        } catch (\Throwable $e) {
            View::clearSections();

            if ($e instanceof ViewException && $e->getOriginalView() !== '') {
                throw $e;
            }

            throw self::createMappedViewException(
                $e,
                $compiledPath,
                $originalView ?: $compiledPath
            );
        } finally {
            restore_error_handler();

            while (ob_get_level() > $initialBufferLevel) {
                ob_end_clean();
            }
        }
    }

    protected static function getSourceMapPath(string $compiledPath): string
    {
        return $compiledPath . '.map.json';
    }

    protected static function createMappedViewException(
        \Throwable $exception,
        string $compiledPath,
        string $originalView
    ): ViewException {
        $compiledLine = self::findCompiledLine($exception, $compiledPath);
        $originalLine = self::mapCompiledLine($compiledPath, $compiledLine);
        $severity = $exception instanceof \ErrorException ? $exception->getSeverity() : E_ERROR;

        $mappedCause = new \ErrorException(
            $exception->getMessage(),
            (int) $exception->getCode(),
            $severity,
            $originalView,
            $originalLine,
            $exception
        );

        return (new ViewException(
            "Error rendering view [{$originalView}] at line {$originalLine}: {$exception->getMessage()}",
            (int) $exception->getCode(),
            $mappedCause
        ))
            ->setOriginalView($originalView)
            ->setOriginalLine($originalLine)
            ->setCompiledView($compiledPath);
    }

    protected static function findCompiledLine(\Throwable $exception, string $compiledPath): int
    {
        if ($exception->getFile() === $compiledPath) {
            return max(1, $exception->getLine());
        }

        foreach ($exception->getTrace() as $frame) {
            if (($frame['file'] ?? null) === $compiledPath) {
                return max(1, (int) ($frame['line'] ?? 1));
            }
        }

        return self::COMPILED_HEADER_LINES + 1;
    }

    protected static function mapCompiledLine(string $compiledPath, int $compiledLine): int
    {
        $mapJson = @file_get_contents(self::getSourceMapPath($compiledPath));
        if ($mapJson !== false) {
            $map = json_decode($mapJson, true);
            if (
                is_array($map)
                && ($map['version'] ?? null) === self::SOURCE_MAP_VERSION
                && isset($map['lines'][$compiledLine])
            ) {
                return max(1, (int) $map['lines'][$compiledLine]);
            }
        }

        // Compatibility fallback for compiled files created before source maps.
        return max(1, $compiledLine - self::COMPILED_HEADER_LINES);
    }
}
